spring:
  application:
    name: lark-example-task

server:
  port: 6001
---
spring:
  config:
    activate:
      on-profile: playground

lark:
  registry:
    address: register-dev.lark-cloud.com:8848

  task:
    address: http://schedule-dev.lark-cloud.com/xxl-job-admin
    token: 12345678

---
spring:
  config:
    activate:
      on-profile: qa

lark:
  registry:
    address: register-qa.alzjqr.cn:8848

  task:
    address: http://task-console-qa.alzjqr.cn/xxl-job-admin
    token: 12345678