spring:
  application:
    name: lark-example-msg-handler

server:
  port: 5001

---
spring:
  config:
    activate:
      on-profile: playground

lark:
  registry:
    address: register-dev.lark-cloud.com:8848

  msg:
    address: mq-dev.lark-cloud.com:9876
    subscriber: true

---
spring:
  config:
    activate:
      on-profile: qa

lark:
  registry:
    address: register-qa.alzjqr.cn:8848

  msg:
    address: mq-qa.alzjqr.cn:9876
    subscriber: true