include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/deploy/java.deploy.gitlab-ci.yml'

variables:
  REGISTRY_ADDRESS: 192.168.99.91:8080
  REGISTRY_IMAGE_PULL_SECRETS: harbor-registry-secret
  PROJECT_NAME: $CI_PROJECT_NAME

build:
  script:
    - build.sh
  artifacts:
    untracked: true
    expire_in: 2 hrs

package_api:
  variables:
    MODULE_NAME: lark-example-api
  extends: .package
  script:
    - export project_dir=$(pwd)
    - cd /$project_dir/$MODULE_NAME
    - package.sh $MODULE_NAME $REGISTRY_ADDRESS $CI_PROJECT_PATH $COMMIT_SHA

package_service:
  variables:
    MODULE_NAME: lark-example-service
  extends: .package
  script:
    - export project_dir=$(pwd)
    - cd /$project_dir/$MODULE_NAME
    - package.sh $MODULE_NAME $REGISTRY_ADDRESS $CI_PROJECT_PATH $COMMIT_SHA

deploy_dev_api:
  variables:
    MODULE_NAME: lark-example-api
    MODULE_TYPE: api
    INGRESS_HOST: api.foo.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 1001
  extends: .deploy-dev
  script:
    - cd /root/deploy/
    - deploy.sh $PROJECT_NAME $MODULE_NAME $REGISTRY_ADDRESS $REGISTRY_IMAGE_PULL_SECRETS $CI_PROJECT_PATH $COMMIT_SHA

deploy_dev_service:
  variables:
    MODULE_NAME: lark-example-service
    MODULE_TYPE: service
    INGRESS_HOST: service.foo.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 3001
  extends: .deploy-dev
  script:
    - cd /root/deploy/
    - deploy.sh $PROJECT_NAME $MODULE_NAME $REGISTRY_ADDRESS $REGISTRY_IMAGE_PULL_SECRETS $CI_PROJECT_PATH $COMMIT_SHA