include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/deploy/java.deploy.gitlab-ci.yml'

build_qa:
  extends: .build_qa

package_api_qa:
  extends: .package_qa
  variables:
    MODULE_NAME: lark-example-api
  script:
    - export project_dir=$(pwd)
    - cd /$project_dir/$MODULE_NAME
    - package.sh

package_service_qa:
  extends: .package_qa
  variables:
    MODULE_NAME: lark-example-service
  script:
    - export project_dir=$(pwd)
    - cd /$project_dir/$MODULE_NAME
    - package.sh

deploy_api_qa:
  extends: .deploy-qa
  variables:
    MODULE_NAME: lark-example-api
    MODULE_TYPE: api
    INGRESS_HOST: techwis-api-qa.sanqlt.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 1001
  script:
    - deploy.sh

deploy_service_qa:
  variables:
    MODULE_NAME: lark-example-service
    MODULE_TYPE: service
    INGRESS_HOST: techwis-service-qa.sanqlt.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 3001
  extends: .deploy-qa
  script:
    - deploy.sh