include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'

variables:
  REGISTRY_ADDRESS: 192.168.99.91:8080

build:
  script:
    - echo $CI_APPLICATION_REPOSITORY
    - echo $CI_PROJECT_PATH