include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'

variables:
  REGISTRY_ADDRESS: 192.168.99.91:8080
  DOCKER_PROJECT_DIST_PATH: $CI_PROJECT_NAME
  MODULE_API_NAME: lark-example-api

build:
  script:
    - build.sh
    - export dir=$(pwd)
    - cp $dir/$MODULE_API_NAME/target/*.jar $dir/$MODULE_API_NAME/dist
  artifacts:
    paths:
      - $MODULE_API_NAME/target/*.jar
    expire_in: 1 hrs

package:
  script:
    - export dir=$(pwd)
    - echo $dir/$MODULE_API_NAME/dist
    - cd $dir/$MODULE_API_NAME/dist
    - package.sh $MODULE_API_NAME $REGISTRY_ADDRESS $CI_PROJECT_PATH $COMMIT_SHA
