include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/deploy/java.deploy.gitlab-ci.yml'

build_sanqlt:
  extends:
    - .sanqlt
    - .build

#Api
package_api_sanqlt:
  extends:
    - .sanqlt
    - .package
  variables:
    MODULE_NAME: lark-example-api

deploy_api_qa_sanqlt:
  extends:
    - .sanqlt
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-api
    MODULE_TYPE: api
    INGRESS_HOST: techwis-api-qa.sanqlt.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 1001


#Service
package_service_sanqlt:
  extends:
    - .sanqlt
    - .package
  variables:
    MODULE_NAME: lark-example-service

deploy_service_qa_sanqlt:
  extends:
    - .sanqlt
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-service
    MODULE_TYPE: service
    INGRESS_HOST: techwis-service-qa.sanqlt.com
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 3001