include:
  - project: 'devops/ci-templates'
    file: '/build/java.build.gitlab-ci.yml'
  - project: 'devops/ci-templates'
    file: '/deploy/java.deploy.gitlab-ci.yml'

build:
  extends:
    - .qa
    - .build

#Api
package_api:
  extends:
    - .qa
    - .package
  variables:
    MODULE_FOLDER_NAME: lark-example-api
    MODULE_NAME: lark-example-api
  script:
    - export project_dir=$(pwd)
    - cd $project_dir/$MODULE_FOLDER_NAME
    - ls -l
    - package.sh

deploy_api_qa:
  extends:
    - .qa
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-api
    MODULE_TYPE: api
    INGRESS_HOST: api-qa.alzjqr.cn
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 1001

#Service
package_service:
  extends:
    - .qa
    - .package
  variables:
    MODULE_FOLDER_NAME: lark-example-service
    MODULE_NAME: lark-example-service

deploy_service_qa:
  extends:
    - .qa
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-service
    MODULE_TYPE: service
    INGRESS_HOST: service-qa.alzjqr.cn
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 3001

#Msg
package_msg:
  extends:
    - .qa
    - .package
  variables:
    MODULE_FOLDER_NAME: lark-example-msg-handler
    MODULE_NAME: lark-example-msg-handler

deploy_msg_qa:
  extends:
    - .qa
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-msg-handler
    MODULE_TYPE: msg-handler
    INGRESS_HOST: handler-qa.alzjqr.cn
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 5001


#Task
package_task:
  extends:
    - .qa
    - .package
  variables:
    MODULE_FOLDER_NAME: lark-example-task
    MODULE_NAME: lark-example-task

deploy_task_qa:
  extends:
    - .qa
    - .deploy_qa
  variables:
    MODULE_NAME: lark-example-task
    MODULE_TYPE: task
    INGRESS_HOST: task-qa.alzjqr.cn
    INGRESS_PATH: /$MODULE_NAME
    CONTAINER_PORT: 6001