spring:
  application:
    name: lark-example-api

server:
  port: 1001

---
spring:
  config:
    activate:
      on-profile: playground

lark:
  registry:
    address: register-dev.lark-cloud.com:8848
  msg:
    address: mq-dev.lark-cloud.com:9876
    publisher: true
  util:
    index:
      address: index-dev.lark-cloud.com:9200
    oss:
      address: oss-dev.lark-cloud.com
      username: minio
      password: 12345678
      type: minio
    cache:
      address: cache-dev.lark-cloud.com:6379
      password: 12345678
  db:
    source:
      - user_master
      - user_slave
      - order_master_0
      - order_master_1
    user_master:
      name: demo
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
      type: mysql
    user_slave:
      name: demo
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
      type: mysql
    order_master_0:
      name: demo_order_0
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
    order_master_1:
      name: demo_order_1
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
    shard:
      - order
    order:
      database: order_master_0, order_master_1
      route: order_master_$->{0..1}.t_order_$->{0..1}
      database-sharding:
        column: user_id
        algorithm: order_master_$->{user_id % 2}
      table-sharding:
        column: order_id
        algorithm: t_order_$->{order_id % 2}

---
spring:
  config:
    activate:
      on-profile: qa

lark:
  registry:
    address: register-qa.sanqlt.com:8848
  msg:
    address: mq-00-namesrv-qa.sanqlt.com:9876
    publisher: true
  util:
    index:
      address: es-00-qa.sanqlt.com:9200
    oss:
      address: minio-qa.sanqlt.com
      username: minio
      password: 1O4iE2BGre7R
      type: minio
    cache:
      address: cache-00-qa.sanqlt.com:6379
      password: ScCuWkb0A0MC
  db:
    source:
      - user_master
      - user_slave
      - ds0
      - ds1
    user_master:
      name: techwis-demo
      address: db-00-qa.sanqlt.com:3306
      username: techwis
      password: wRcVxyxzJ@gKp4e6dGf.uzLu
      type: mysql
    user_slave:
      name: techwis-demo
      address: db-00-qa.sanqlt.com:3306
      username: techwis
      password: wRcVxyxzJ@gKp4e6dGf.uzLu
      type: mysql
    ds0:
      name: demo_order_0
      address: db-00-qa.sanqlt.com:3306
      username: techwis
      password: wRcVxyxzJ@gKp4e6dGf.uzLu
    ds1:
      name: demo_order_1
      address: db-00-qa.sanqlt.com:3306
      username: techwis
      password: wRcVxyxzJ@gKp4e6dGf.uzLu
    shard:
      - t_order
    t_order:
      database: ds0, ds1
      route: ds$->{0..1}.t_order_$->{0..1}
      database-sharding:
        column: user_id
        algorithm: ds$->{user_id % 2}
      table-sharding:
        column: order_id
        algorithm: t_order_$->{order_id % 2}