spring:
  application:
    name: lark-example-api

server:
  port: 1001

---
spring:
  config:
    activate:
      on-profile: playground

lark:
  registry:
    address: register-dev.lark-cloud.com:8848
  msg:
    address: mq-dev.lark-cloud.com:9876
    publisher: true
  util:
    index:
      address: index-dev.lark-cloud.com:9200
    oss:
      address: oss-dev.lark-cloud.com
      username: minio
      password: 12345678
      type: minio
    cache:
      address: cache-dev.lark-cloud.com:6379
      password: 12345678
  db:
    source:
      - user_master
      - user_slave
      - order_master_0
      - order_master_1
    user_master:
      name: demo
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
      type: mysql
    user_slave:
      name: demo
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
      type: mysql
    order_master_0:
      name: demo_order_0
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
    order_master_1:
      name: demo_order_1
      address: db-dev.lark-cloud.com:3306
      username: lark
      password: 12345678
    shard:
      - order
    order:
      database: order_master_0, order_master_1
      route: order_master_$->{0..1}.t_order_$->{0..1}
      database-sharding:
        column: user_id
        algorithm: order_master_$->{user_id % 2}
      table-sharding:
        column: order_id
        algorithm: t_order_$->{order_id % 2}

---
spring:
  config:
    activate:
      on-profile: qa

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
    percentiles:
      http.server.requests: 0.95, 0.99
      sla.http.server.requests: 200ms
    tags:
      application: ${spring.application.name}
      
lark:
  registry:
    address: register-qa.alzjqr.cn:8848
  msg:
    address: mq-qa.alzjqr.cn:9876
    publisher: true
  util:
    index:
      address: es-qa.alzjqr.cn:9200
    oss:
      address: oss-qa.alzjqr.cn
      username: minio
      password: 12345678
      type: minio
    cache:
      address: cache-qa.alzjqr.cn:6379
      #password: qwe123
  db:
    source:
      - user_master
      - user_slave
      - order_master_0
      - order_master_1
    user_master:
      name: demo
      address: db-qa.alzjqr.cn:3306
      username: root
      password: root
      type: mysql
    user_slave:
      name: demo
      address: db-qa.alzjqr.cn:3306
      username: root
      password: root
      type: mysql
    order_master_0:
      name: demo_order_0
      address: db-qa.alzjqr.cn:3306
      username: root
      password: root
    order_master_1:
      name: demo_order_1
      address: db-qa.alzjqr.cn:3306
      username: root
      password: root
    shard:
      - order
    order:
      database: order_master_0, order_master_1
      route: order_master_$->{0..1}.t_order_$->{0..1}
      database-sharding:
        column: user_id
        algorithm: order_master_$->{user_id % 2}
      table-sharding:
        column: order_id
        algorithm: t_order_$->{order_id % 2}