spring:
  application:
    name: lark-example-service

server:
  port: 8001

---
spring:
  profiles: default
  cloud:
    nacos:
      discovery:
        server-addr: lark-dep-env.foo.com:8848

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://lark-dep-env.foo.com:6379
          password: 12345678
          subscriptionConnectionMinimumIdleSize: 10
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 10
          connectionPoolSize: 64
          database: 0

  datasource:
    url: jdbc:mysql://lark-dep-env.foo.com:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: lark
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

rocketmq:
  name-server: lark-dep-env.foo.com:9876
  producer:
    group: lark-example-service